Retailer.WebUi/Models/Cart/CartItemModel.cs
namespace Retailer.WebUi.Models.Cart
{
    public class CartItemModel
    {
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public string RentPeriodInDays { get; set; }
    }
}

Retailer.WebUi/Models/Cart/CartModelFactory.cs
using System;
using System.Globalization;
using System.Linq;
using Contracts;

namespace Retailer.WebUi.Models.Cart
{
    public class CartModelFactory
    {
        public IndexViewModel CreateIndexViewModel(Domain.Entities.Cart cart)
        {
            return new IndexViewModel
            {
                CartId = cart.Id.ToString(),
                IsCartConfirmed = cart.IsConfirmed,
                CartStatusInfo = GetCartStatusInfo(cart),
                CartItems = cart.CartItems.Select(cartItem => new CartItemModel
                {
                    ProductName = cartItem.ProductName,
                    ProductType = cartItem.ProductType.GetProductTypeDisplayName(),
                    RentPeriodInDays = cartItem.RentPeriodInDays.ToString(),
                })
                .OrderBy(cartItem => cartItem.ProductType)
                .ThenBy(cartItem => cartItem.ProductName)
                .ToList()
            };
        }

        private string GetCartStatusInfo(Domain.Entities.Cart cart)
        {
            if (!cart.IsConfirmed)
            {
                return "Not confirmed";
            }

            switch (cart.OrderStatusCode)
            {
                case OrderStatusCode.Success:
                    return "Warehouse: Success.";
                case OrderStatusCode.OutOfStock:
                    return "Warehouse: One or more items you have ordered are out of stock. Please create a new order.";
                case OrderStatusCode.InternalError:
                    return "Warehouse: Internal error.";
                case null:
                    return "Cart is confirmed. Waiting for warehouse response.";
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
    }
}

Retailer.WebUi/Models/Cart/IndexViewModel.cs
using System.Collections.Generic;

namespace Retailer.WebUi.Models.Cart
{
    public class IndexViewModel
    {
        public List<CartItemModel>  CartItems { get; set; }
        public bool IsCartConfirmed { get; set; }
        public string CartStatusInfo { get; set; }
        public string CartId { get; set; }
    }
}

Retailer.WebUi/Controllers/CartController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Retailer.Domain;
using Retailer.Messaging;
using Retailer.WebUi.Models.Cart;
using Retailer.WebUi.Models.Home;

namespace Retailer.WebUi.Controllers
{
    public class CartController : BaseController
    {
        private readonly CartModelFactory _cartModelFactory;
        private readonly OrderCommandSender _orderEventPublisher;
        private readonly IProductContext _productContext;
        private readonly ICartContext _cartContext;

        public CartController(CartModelFactory cartModelFactory,
            OrderCommandSender orderEventPublisher,
            IProductContext productContext, 
            ICartContext cartContext)
        {
            _cartModelFactory = cartModelFactory;
            _orderEventPublisher = orderEventPublisher;
            _productContext = productContext;
            _cartContext = cartContext;
        }

        public async Task<ActionResult> Index()
        {
            var cart = await _cartContext.GetOrCreateCartAsync(SessionsCartId);
            var viewModel = _cartModelFactory.CreateIndexViewModel(cart);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddItemToCart(AddItemToCartPostModel model)
        {
            if (ModelState.IsValid)
            {
                var cart = await _cartContext.GetOrCreateCartAsync(SessionsCartId);
                var productToRent = await _productContext.FindProductByIdOrDefaultAsync(model.ProductId);

                cart.AddItem(productToRent, model.RentPeriodInDays);

                await _cartContext.SaveChangesAsync();
            }

            return RedirectToLocal(model.ReturnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmCart(string returnUrl)
        {
            var cart = await _cartContext.GetOrCreateCartAsync(SessionsCartId);

            cart.ConfirmCart();

            await _cartContext.SaveChangesAsync();

            _orderEventPublisher.PlaceOrder(cart);

            return RedirectToLocal(returnUrl);
        }
    }
}

Retailer.WebUi/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Retailer.Domain;
using Retailer.WebUi.Models;

namespace Retailer.WebUi.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly InvoiceGenerator _invoiceGenerator;
        private readonly ICartContext _cartContext;

        public InvoiceController(InvoiceGenerator invoiceGenerator, ICartContext cartContext)
        {
            _invoiceGenerator = invoiceGenerator;
            _cartContext = cartContext;
        }

        public async Task<FileResult> DownloadInvoiceInPlainText(Guid cartId)
        {
            var cart = await _cartContext.GetOrCreateCartAsync(cartId);
            var reportBytes = await _invoiceGenerator.GeneratePlainTextInvoiceAsync(cart);

            return File(reportBytes, "text/plain", "Invoice.txt");
        }
    }
}

Retailer.WebUi/Views/Cart/Index.cshtml
@using Retailer.WebUi.Models.Cart
@model Retailer.WebUi.Models.Cart.IndexViewModel

@{
    ViewBag.Title = "My cart";
}

<div class="row">
    <div class="col-md-8">

        @if (Model.CartItems.Any())
        {
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Product name</th>
                        <th>Type</th>
                        <th>Rent period in days</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (CartItemModel cartItemModel in Model.CartItems)
                {
                        <tr>
                            <td>@cartItemModel.ProductName</td>
                            <td>@cartItemModel.ProductType</td>
                            <td>@cartItemModel.RentPeriodInDays</td>
                        </tr>
                    }

                </tbody>
            </table>


            using (Html.BeginForm("ConfirmCart", "Cart", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()

                <input type="hidden" name="returnUrl" value="@Request.RawUrl" />

                <div class="form-group">
                    <label class="col-sm-2 control-label">Cart status:</label>
                    <div class="col-sm-10">
                        <p class="form-control-static">@Model.CartStatusInfo</p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Invoice:</label>
                    <div class="col-sm-10">
                        <p class="form-control-static">

                            @if (Model.IsCartConfirmed)
                            {
                                @Html.ActionLink("Download", "DownloadInvoiceInPlainText", "Invoice", new
                           {
                               CartId = Model.CartId
                           }, null)
                            }

                        </p>
                    </div>
                </div>

                if (!Model.IsCartConfirmed)
                {
                    <input type="submit" class="btn btn-primary" value="Confirm cart" />
                }
            }
        }
        else
        {
            <div class="alert alert-warning">

                <span class="glyphicon glyphicon-info-sign"></span>

                You cart is empty.
            </div>
        }

    </div>
</div>